#数据源一[数据库已加密]
master:
  jdbc:
    url: jdbc:mysql://132.232.64.127:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: mQCiBQuTD/D1eiSvN/gFWA==
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWaitMillis: 60000
    timeBetweenEvictionRunsMillis: 60000
slave:
  jdbc:
    url: jdbc:mysql://132.232.64.127:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: mQCiBQuTD/D1eiSvN/gFWA==
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWaitMillis: 60000
    timeBetweenEvictionRunsMillis: 60000

#跨域域名限制访问
admin:
  host: http://127.0.0.1:3000
app:
  host: http://127.0.0.1:3400
