server:
  port: 8888

spring:
  profiles:
    active: dev, redis

#mybatis配置
mybatis:
  typeAliasesPackage: wang.yobbo.**.model
  mapperLocations: classpath*:wang/yobbo/**/mapper/*Mapper.xml
  configLocation: classpath:mybatis-config.xml