#数据源一
master:
  jdbc:
    url: jdbc:mysql://dbserver:3306/zheng?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: rWd3Hb+AzNg3IXF1b5vD+g==
slave:
  jdbc:
    url: jdbc:mysql://dbserver:3306/zheng?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: rWd3Hb+AzNg3IXF1b5vD+g==

#mybatis配置
mybatis:
  typeAliasesPackage: wang.yobbo.**.entity
  mapperLocations: classpath*:wang/yobbo/**/mapper/*Mapper.xml
  configLocation: classpath:mybatis-config.xml
